version: "3.9"

services:
  backend:
    build: ./email-cleanup-app/backend
    container_name: cleanup_backend
    ports:
      - "8001:8000"
    volumes:
      - ./email-cleanup-app/backend/temp_uploads:/app/temp_uploads:rw
    env_file:
      - ./email-cleanup-app/.env
    environment:
      - IS_DOCKER=true
      - POSTGRES_USER=cleanup_user
      - POSTGRES_PASSWORD=cleanup_pass
      - POSTGRES_DB=cleanup_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: cleanup_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cleanup_user
      POSTGRES_PASSWORD: cleanup_pass
      POSTGRES_DB: cleanup_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./email-cleanup-app/backup.sql:/docker-entrypoint-initdb.d/backup.sql


  frontend:
    build: ./rv-cleanup-ui
    container_name: cleanup_frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

volumes:
  pgdata:
