version: "3.9"

services:
  backend:
    build: ./backend
    container_name: cleanup_backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend/temp_uploads:/app/temp_uploads
    env_file:
      - .env
    environment:
      - IS_DOCKER=true
      - POSTGRES_USER=cleanup_user
      - POSTGRES_PASSWORD=cleanup_pass
      - POSTGRES_DB=cleanup_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: cleanup_db
    restart: always
    environment:
      POSTGRES_USER: cleanup_user
      POSTGRES_PASSWORD: cleanup_pass
      POSTGRES_DB: cleanup_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # 👈 Use named volume

volumes:
  pgdata:  # 👈 Declare it explicitly here
