version: "3.9"
services:
  backend:
    build: ./backend
    container_name: cleanup_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
  db:
    image: postgres:15
    container_name: cleanup_db
    restart: always
    environment:
      POSTGRES_USER: cleanup_user
      POSTGRES_PASSWORD: cleanup_pass
      POSTGRES_DB: cleanup_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

